#!/usr/bin/env bash
set -euo pipefail

# https://www.raspberrypi-spy.co.uk/2014/11/enabling-the-i2c-interface-on-the-raspberry-pi/
echo "Enable I2C via Interface Options -> I2C"
sudo raspi-config

# dependencies
sudo apt-get install git -y
pip3 install --user --break-system-packages adafruit-circuitpython-ht16k33 requests

if [ ! -d rpi-weather ]
then
  git clone https://github.com/joshblum/rpi-weather.git
fi

(cd rpi-weather && cp climacell_cfg_template.json climacell_cfg.json)
echo "dependencies downloaded, please fill out climacell_cfg.json to run"

rm -- "$0"
