#!/usr/bin/env bash
set -euo pipefail

sudo raspi-config

# dependencies
sudo apt-get update
sudo apt-get install build-essential python-dev
sudo apt-get install python-smbus python-pil
git clone https://github.com/adafruit/Adafruit_Python_LED_Backpack.git
cd Adafruit_Python_LED_Backpack && sudo python3 setup.py install

cd .. && git clone https://github.com/joshblum/rpi-weather.git
echo "dependencies downloaded, please fill out climacell_cfg_template.json to run"

cd - && rm -- "$0"
